name: Publish Docker image

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: docker.io
          image: vasu0494/python-flask

